export const numbers = [
  { label: 'C', value: 'clear' },
  { label: '7', value: '7' },
  { label: '4', value: '4' },
  { label: '1', value: '1' },
  { label: '0', value: '0' },
  { label: '/', value: '/' },
  { label: '8', value: '8' },
  { label: '5', value: '5' },
  { label: '2', value: '2' },
  { label: '.', value: '.' },
  { label: 'x', value: '*' },
  { label: '9', value: '9' },
  { label: '6', value: '6' },
  { label: '3', value: '3' },
  { label: '', value: 'null' },
  { label: '-', value: '-' },
  { label: '+', size: '2', value: '+' },
  { label: '=', size: "2", value: 'equal' },
];